### ISSUE TITLE
Soccer is wrong

### ISSUE THREAD

**Issue by maxbiostat** [IgorMichels/Brazilian_Football#1]
Football is the correct name ;-)

**Comment by IgorMichels** [comment]
Thanks!

**Comment by maxbiostat** [comment]
You do know that was a joke, right? In British  English we usually say football, whereas American English employs soccer. This is despite the  term soccer having originated in the UK.

**Comment by IgorMichels** [comment]
I didn't know the final part, but I just decided to join in the joke ;-)

This is similar to Portuguese, where there are differences between Portuguese-BR and Portuguese-PT: "baliza" = "gol", for example

**Comment by maxbiostat** [comment]
For historical book keeping : [Why americans call it soccer?](https://www.businessinsider.com/why-americans-call-it-soccer-2014-6#:~:text=The%20word%20%22soccer%22%20comes%20from,it%2C%20all%20under%20different%20rules.&text=%22Association%20football%22%20became%20%22soccer.%22)
